matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - git
            - build-essential
            - cmake
            - libboost-all-dev
            - libpng-dev
      env:
        - MATRIX_EVAL="update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5"

    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
            - git
            - build-essential
            - cmake
            - libboost-all-dev
            - libpng-dev
      env:
        - MATRIX_EVAL="update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6"

    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - git
            - build-essential
            - cmake
            - libboost-all-dev
            - libpng-dev
      env:
        - MATRIX_EVAL="update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 --slave /usr/bin/g++ g++ /usr/bin/g++-7"
        
sudo: required
services:
  - docker
  
before_install:
  - eval "sudo ${MATRIX_EVAL}"
  - sudo update-alternatives --config gcc
      
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DREPLAY_USE_STBIMAGE=OFF -DREPLAY_ENABLE_UNIT_TESTS=OFF ..
  - cmake --build .
