linux: &linux
  language: cpp
  os: linux
  dist: xenial
  addons:
    apt:
      update: true
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - git
        - build-essential
        - cmake
        - python3-pip
          
matrix:
  include:
    - <<: *linux
      env:
        - MATRIX_EVAL="apt-get install g++-6 && CC=gcc-6 && CXX=g++-6 && CONAN_USER_HOME=/tmp/conan

    - <<: *linux
      env:
        - MATRIX_EVAL="apt-get install g++-7 && CC=gcc-7 && CXX=g++-7 && CONAN_USER_HOME=/tmp/conan
        
sudo: required

cache:
  directories:
  - $CONAN_USER_HOME

before_install:
  - eval "${MATRIX_EVAL}"
  - pip3 install --upgrade setuptools
  - pip3 install conan
  - conan config install conan_config/

script:
  - mkdir build && cd build
  - conan install .. -s compiler.libcxx=libstdc++
  - cmake -DCMAKE_BUILD_TYPE=Release -DReplay_USE_CONAN=ON -DReplay_ENABLE_UNIT_TESTS=OFF -DReplay_USE_STBIMAGE=OFF -DReplay_USE_LIBPNG=OFF ..
  - cmake --build .
