sudo: required
services:
  - docker
  
before_install:
  - docker pull ubuntu:zesty
  - docker run -itd --name build ubuntu:zesty

script:
  - docker exec build apt update > /dev/null
  - docker exec build apt dist-upgrade -y > /dev/null
  - docker exec build apt install git build-essential cmake libboost-all-dev -y > /dev/null
  - docker exec build git clone https://github.com/ltjax/file_monitor.git /source
  - docker exec build cmake -DCMAKE_BUILD_TYPE=Release -B/build -H/source
  - docker exec build cmake --build /build
