language: cpp
matrix:
  include:
    - os: linux
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - git
            - build-essential
            - cmake
            - python3-pip
      env:
        - MATRIX_EVAL="update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9" CONAN_USER_HOME=/tmp/conan
        
sudo: required

cache:
  directories:
  - $CONAN_USER_HOME

before_install:
  - eval "sudo ${MATRIX_EVAL}"
  - sudo update-alternatives --config gcc
  - wget https://dl.bintray.com/conan/installers/conan-ubuntu-64_1_20_5.deb
  - sudo dpkg -i ./conan-ubuntu-64_1_20_5.deb
  - conan --version
  - conan config install conan_config/

script:
  - mkdir build && cd build
  - conan install .. -s compiler.libcxx=libstdc++
  - cmake -DCMAKE_BUILD_TYPE=Release -DReplay_USE_CONAN=ON -DReplay_ENABLE_UNIT_TESTS=OFF -DReplay_USE_STBIMAGE=OFF -DReplay_USE_LIBPNG=OFF ..
  - cmake --build .
