
env:
  global:
    - CONAN_USER_HOME: "/tmp/conan"

linux: &linux
  os: linux
  dist: xenial
  language: cpp
  addons:
    apt:
      update: true
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - git
        - build-essential
        - cmake
        - python3-pip
matrix:
  include:
    - <<: *linux
      env: GCC_VERSION=9 
        
sudo: required

cache:
  directories:
  - $CONAN_USER_HOME

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
